model_args:
  use_cuda: True
  encoder_size: 64
  decoder_size: 128
  in_length: 9
  out_length: 15
  grid_size: [13, 3]
  soc_conv_depth: 64
  conv_3x1_depth: 16
  dyn_embedding_size: 32
  input_embedding_size: 32
  num_lat_classes: 3
  num_lon_classes: 2
  use_maneuvers: False

dataset_args:
  nbr_mode: 6

train_args:
  pretrain_epochs: 30
  train_epochs: 270
  batch_size: 512

data_paths:
  train_set: 'highD/mmap/split_712/train'
  val_set:   'highD/mmap/split_712/val'
  test_set:  'highD/mmap/split_712/test'
  save_dir:  'ckpts/importance'